services:
  postgres:
    image: postgres:16
    container_name: ato-postgres
    environment:
      POSTGRES_USER: ato
      POSTGRES_PASSWORD: ato_pass
      POSTGRES_DB: ato_db
    ports:
      - "5432:5432"
    volumes:
      - ato_pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: ato-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

volumes:
  ato_pgdata: